evaluate-commands %sh{
  for file in "$kak_config/rc/"*".kak"; do
    echo "source '$file'"
  done
}

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript) %{
    lsp-enable-window
}

map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
